services:
    blog.domain.repository.user:
        class: Blog\DomainBundle\Infrastructure\IRepository
        factory_service: blog.domain.infrastructure.doctrine.factory
        factory_method: createUserRepository
        public: false

    blog.domain.repository.post:
        class: Blog\DomainBundle\Infrastructure\IRepository
        factory_service: blog.domain.infrastructure.doctrine.factory
        factory_method: createPostRepository
        public: false

    blog.domain.repository.comment:
        class: Blog\DomainBundle\Infrastructure\IRepository
        factory_service: blog.domain.infrastructure.doctrine.factory
        factory_method: createCommentRepository
        public: false
