services:
    blog.domain.service.user:
        class: Blog\DomainBundle\Service\UserService
        arguments: [@blog.domain.unit_of_work, @blog.domain.repository.user]

    blog.domain.service.post:
        class: Blog\DomainBundle\Service\PostService
        arguments: [@blog.domain.unit_of_work, @blog.domain.repository.post]

    blog.domain.service.comment:
        class: Blog\DomainBundle\Service\CommentService
        arguments: [@blog.domain.unit_of_work, @blog.domain.repository.comment]
